/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.hsb.mvpmsmessage.api;

import javax.validation.Valid;

import org.springframework.data.domain.Pageable;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.NonNull;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

import com.hsb.mvpmsmessage.annotation.JwtIgnore;
import com.hsb.mvpmsmessage.constant.Swagger2Constants;
import com.hsb.mvpmsmessage.model.payload.ExceptionResponse;
import com.hsb.mvpmsmessage.model.payload.request.ChatRequest;
import com.hsb.mvpmsmessage.model.payload.response.ChatResponse;
import com.hsb.mvpmsmessage.model.payload.response.CountResponse;
import com.hsb.mvpmsmessage.model.payload.response.DelNotificationResponse;
import com.hsb.mvpmsmessage.model.payload.response.GetATResponse;
import com.hsb.mvpmsmessage.model.payload.response.GetCommentsResponse;
import com.hsb.mvpmsmessage.model.payload.response.GetLikesResponse;
import com.hsb.mvpmsmessage.model.payload.response.GetNotificaitonsResponse;
import com.hsb.mvpmsmessage.model.payload.response.GetSystemResponse;
import com.hsb.mvpmsmessage.model.payload.response.InitDataResponse;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiImplicitParam;
import io.swagger.annotations.ApiImplicitParams;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import springfox.documentation.annotations.ApiIgnore;

@Api(tags = "MvpMs Message Module", description = "The MvpMS Message Module API")
public interface MvpMsMessageModuleApi {

	@JwtIgnore
	@ApiOperation(value = "Get Unread Notifications Count", nickname = "getUnreadNotificationsCount", notes = "Get Unread Notifications Count", response = CountResponse.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_200, response = CountResponse.class),
        @ApiResponse(code = 400, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_400, response = ExceptionResponse.class),
        @ApiResponse(code = 500, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_500, response = ExceptionResponse.class)})
	@GetMapping(value = "/notificaitons/count", produces = MediaType.APPLICATION_JSON_VALUE)
    ResponseEntity<CountResponse> getUnreadNotificationsCount(@ApiParam(value = "user Id", required = true) @RequestParam(value = "userId", required = true) Integer userId);
	

	@JwtIgnore
	@ApiOperation(value = "Get Notifications", nickname = "getNotifications", notes = "Get Notifications", response = GetNotificaitonsResponse.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_200, response = GetNotificaitonsResponse.class),
        @ApiResponse(code = 400, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_400, response = ExceptionResponse.class),
        @ApiResponse(code = 500, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_500, response = ExceptionResponse.class)})
	@ApiImplicitParams({
        @ApiImplicitParam(name = "page", dataType = "int", paramType = "query", defaultValue = "1", example = "1", value = "Results page you want to retrieve (1..N)"),
        @ApiImplicitParam(name = "size", dataType = "int", paramType = "query", defaultValue = "10", example = "10", value = "Number of records per page.")
	})
	@GetMapping(value = "/notifications", produces = MediaType.APPLICATION_JSON_VALUE)
    ResponseEntity<GetNotificaitonsResponse> getNotifications(@ApiIgnore @NonNull Pageable pageable, @ApiParam(value = "user Id", required = true) @RequestParam(value = "userId", required = true) Integer userId);
	
	
	@JwtIgnore
	@ApiOperation(value = "Delete Notificaiton", nickname = "deleteNotificaiton", notes = "Delete Notificaiton", response = DelNotificationResponse.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_200, response = DelNotificationResponse.class),
        @ApiResponse(code = 400, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_400, response = ExceptionResponse.class),
        @ApiResponse(code = 500, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_500, response = ExceptionResponse.class)})
    @DeleteMapping(value = "/Notification/del", produces = MediaType.APPLICATION_JSON_VALUE)
    ResponseEntity<DelNotificationResponse> deleteNotificaiton(@ApiParam(value = "message id", required = true) @Validated @RequestParam(value = "msgId", required = true) Integer msgId);

	
	@JwtIgnore
	@ApiOperation(value = "Get System Message", nickname = "getSystemMessage", notes = "Get System Message", response = GetSystemResponse.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_200, response = GetSystemResponse.class),
        @ApiResponse(code = 400, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_400, response = ExceptionResponse.class),
        @ApiResponse(code = 500, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_500, response = ExceptionResponse.class)})
	@ApiImplicitParams({
        @ApiImplicitParam(name = "page", dataType = "int", paramType = "query", defaultValue = "1", example = "1", value = "Results page you want to retrieve (1..N)"),
        @ApiImplicitParam(name = "size", dataType = "int", paramType = "query", defaultValue = "10", example = "10", value = "Number of records per page.")
	})
	@GetMapping(value = "/notifications/system", produces = MediaType.APPLICATION_JSON_VALUE)
    ResponseEntity<GetSystemResponse> getSystemMessage(@ApiIgnore @NonNull Pageable pageable, @ApiParam(value = "user id", required = true) @RequestParam(value = "userId", required = true) Integer userId);
	
	
	@JwtIgnore
	@ApiOperation(value = "Get Likes", nickname = "getLikes", notes = "Get Likes", response = GetLikesResponse.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_200, response = GetLikesResponse.class),
        @ApiResponse(code = 400, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_400, response = ExceptionResponse.class),
        @ApiResponse(code = 500, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_500, response = ExceptionResponse.class)})
	@ApiImplicitParams({
        @ApiImplicitParam(name = "page", dataType = "int", paramType = "query", defaultValue = "1", example = "1", value = "Results page you want to retrieve (1..N)"),
        @ApiImplicitParam(name = "size", dataType = "int", paramType = "query", defaultValue = "10", example = "10", value = "Number of records per page.")
	})
	@GetMapping(value = "/likes", produces = MediaType.APPLICATION_JSON_VALUE)
    ResponseEntity<GetLikesResponse> getLikes(@ApiIgnore @NonNull Pageable pageable, @ApiParam(value = "user Id", required = true) @RequestParam(value = "userId", required = true) Integer userId);
	
	
	@JwtIgnore
	@ApiOperation(value = "Get AT Me", nickname = "getATMe", notes = "Get AT Me", response = GetATResponse.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_200, response = GetATResponse.class),
        @ApiResponse(code = 400, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_400, response = ExceptionResponse.class),
        @ApiResponse(code = 500, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_500, response = ExceptionResponse.class)})
	@ApiImplicitParams({
        @ApiImplicitParam(name = "page", dataType = "int", paramType = "query", defaultValue = "1", example = "1", value = "Results page you want to retrieve (1..N)"),
        @ApiImplicitParam(name = "size", dataType = "int", paramType = "query", defaultValue = "10", example = "10", value = "Number of records per page.")
	})
	@GetMapping(value = "/ATme", produces = MediaType.APPLICATION_JSON_VALUE)
    ResponseEntity<GetATResponse> getATMe(@ApiIgnore @NonNull Pageable pageable, @ApiParam(value = "user Id", required = true) @RequestParam(value = "userId", required = true) Integer userId);

		
	@JwtIgnore
	@ApiOperation(value = "Get Comments", nickname = "getComments", notes = "Get Comments", response = GetCommentsResponse.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_200, response = GetCommentsResponse.class),
        @ApiResponse(code = 400, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_400, response = ExceptionResponse.class),
        @ApiResponse(code = 500, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_500, response = ExceptionResponse.class)})
	@ApiImplicitParams({
        @ApiImplicitParam(name = "page", dataType = "int", paramType = "query", defaultValue = "1", example = "1", value = "Results page you want to retrieve (1..N)"),
        @ApiImplicitParam(name = "size", dataType = "int", paramType = "query", defaultValue = "10", example = "10", value = "Number of records per page.")
	})
	@GetMapping(value = "/comments", produces = MediaType.APPLICATION_JSON_VALUE)
    ResponseEntity<GetCommentsResponse> getComments(@ApiIgnore @NonNull Pageable pageable, @ApiParam(value = "user Id", required = true) @RequestParam(value = "userId", required = true) Integer userId);
	
	
	@JwtIgnore
	@ApiOperation(value = "Chat", nickname = "chat", notes = "Chat", response = ChatResponse.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ChatResponse.class),
        @ApiResponse(code = 400, message = "Bad Request", response = ExceptionResponse.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = ExceptionResponse.class)})
    @GetMapping(value = "/message/chat", produces = MediaType.APPLICATION_JSON_VALUE)
    ResponseEntity<ChatResponse> chat(@ApiParam(value = "Chat Request", required = true) @Valid @RequestBody ChatRequest chatRequest);
	
	
	@JwtIgnore
    @ApiOperation(value = "Run Data Initialization", nickname = "initData", notes = "Run Data Initialization", response = InitDataResponse.class)
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_200, response = InitDataResponse.class),
            @ApiResponse(code = 400, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_400, response = ExceptionResponse.class),
            @ApiResponse(code = 500, message = Swagger2Constants.HTTP_STATUS_CODE_MSG_500, response = ExceptionResponse.class)})
    @GetMapping(value = "/loadInitData", produces = MediaType.APPLICATION_JSON_VALUE)
    ResponseEntity<InitDataResponse> initData();
    
}
