server:
   port: 8081
   servlet:
      context-path: /yours
    
#mysql config
spring:
   datasource:
      url: jdbc:mysql://12.1.1.30:3306/mvptest?autoReconnect=yes&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
   redis:
      host: 12.1.1.30
      port: 6379
      password: 123456
      database: 6
    
mybatis-plus:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.hsb.mvpmsuser.model.domain
   configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
    
#jwt config
jwt:
   auth-header-key: Authorization
   token-prefix: Bearer
   # 密钥, 经过Base64加密, 可自行替换
   base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
   # 过期时间，时间戳
   expiresSecond: 172800
