spring:
   message-datasource:
      jdbcUrl: jdbc:mysql://12.1.1.30:3306/mvptest?autoReconnect=yes&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      platform: mysql
 
server:
   port: 9001
   servlet:
      context-path: /mvp-ms-message

mybatis:
   table:
      auto: none
   model:
      pack: com.hsb.mvpmsmessage.model
   database:
      type: mysql
      
mybatis-plus:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.hsb.mvpmsmessage.model
#   configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   global-config:
     id-type: 0
     field-strategy: 2
     capital-mode: true
     refresh-mapper: true
     
#jwt config
jwt:
   auth-header-key: Authorization
   token-prefix: Bearer
   # 密钥, 经过Base64加密, 可自行替换
   base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
   # 过期时间，时间戳
   expiresSecond: 172800
